### ISSUE TITLE
Bad Params in Calls from Client to Mary?

### ISSUE THREAD

**Issue by brianfeister** [googlecreativelab/aiexperiments-giorgio-cam#3]
This could also be some other aspect of the Python server, but spinning up Google Cloud SDK and running this project, I get a server error from the following call in my server logs.

Parameters like `effect_F0Add_parameters=f0Add%3A20.0%3B&effect_Rate_selected` feel like there must be some wrong encoding going on but I'm not sure if it's the client or server that's wrongly encoding, and perhaps the encoding works fine. My `google-cloud-sdk` is `google-cloud-sdk-143.0.1-darwin-x86_64.tar.gz`, so version `143.0.1`

`
http://127.0.0.1:59125/process?INPUT_TYPE=TEXT&OUTPUT_TYPE=AUDIO&INPUT_TEXT=Okay%2C%20I%20am%20shutting%20down&VOICE_SELECTIONS=cmu-bdl-hsmm%20en_US%20male%20hmm&AUDIO_OUT=WAVE_FILE&LOCALE=en_US&VOICE=cmu-bdl-hsmm&AUDIO=WAVE_FILE&effect_F0Scale_selected=on&effect_F0Scale_parameters=f0Scale%3A1.5%3B&effect_TractScaler_selected=on&effect_TractScaler_parameters=amount%3A0.9%3B&effect_F0Add_selected=on&effect_F0Add_parameters=f0Add%3A20.0%3B&effect_Rate_selected=on&effect_Rate_parameters=durScale%3A1.11111111111%3B
http://127.0.0.1:59125/process?INPUT_TYPE=TEXT&OUTPUT_TYPE=AUDIO&INPUT_TEXT=I%27m%20too%20popular%20right%20now.%20I%27ve%20got%20to%20shut%20down.&VOICE_SELECTIONS=cmu-bdl-hsmm%20en_US%20male%20hmm&AUDIO_OUT=WAVE_FILE&LOCALE=en_US&VOICE=cmu-bdl-hsmm&AUDIO=WAVE_FILE&effect_F0Scale_selected=on&effect_F0Scale_parameters=f0Scale%3A1.5%3B&effect_TractScaler_selected=on&effect_TractScaler_parameters=amount%3A0.9%3B&effect_F0Add_selected=on&effect_F0Add_parameters=f0Add%3A20.0%3B&effect_Rate_selected=on&effect_Rate_parameters=durScale%3A1.11111111111%3B
http://127.0.0.1:59125/process?INPUT_TYPE=TEXT&OUTPUT_TYPE=AUDIO&INPUT_TEXT=That%27s%20an%20error%21%20Take%20another.&VOICE_SELECTIONS=cmu-bdl-hsmm%20en_US%20male%20hmm&AUDIO_OUT=WAVE_FILE&LOCALE=en_US&VOICE=cmu-bdl-hsmm&AUDIO=WAVE_FILE&effect_F0Scale_selected=on&effect_F0Scale_parameters=f0Scale%3A1.5%3B&effect_TractScaler_selected=on&effect_TractScaler_parameters=amount%3A0.9%3B&effect_F0Add_selected=on&effect_F0Add_parameters=f0Add%3A20.0%3B&effect_Rate_selected=on&effect_Rate_parameters=durScale%3A0.909090909091%3B
WARNING  2017-02-13 22:16:57,567 urlfetch_stub.py:550] Stripped prohibited headers from URLFetch request: ['Host']
WARNING  2017-02-13 22:16:57,570 urlfetch_stub.py:550] Stripped prohibited headers from URLFetch request: ['Host']
WARNING  2017-02-13 22:16:57,572 urlfetch_stub.py:550] Stripped prohibited headers from URLFetch request: ['Host']
ERROR    2017-02-13 22:16:57,585 webapp2.py:1552] HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/Users/brianfeister/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1535, in __call__
`

**Comment by brianfeister** [comment]
Not sure is this is just a version issue with google-cloud-sdk, but it seems unlikely. Any thoughts @tambien?

**Comment by tambien** [comment]
Maybe it has to do with the version of MaryTTS that you're running. I believe i'm running a 5.2 preview that came out last fall. It's possible that their API has changed slightly. 

Are you getting any errors in the terminal that you're running MaryTTS in?

**Comment by brianfeister** [comment]
Hmmm... I downgraded my `MaryTTS` install and ran the 5.2 server, with the same results:

`HTTPError: HTTP Error 400: Bad Request
http://127.0.0.1:59125/process?INPUT_TYPE=TEXT&OUTPUT_TYPE=AUDIO&INPUT_TEXT=One%20more%20time&VOICE_SELECTIONS=cmu-bdl-hsmm%20en_US%20male%20hmm&AUDIO_OUT=WAVE_FILE&LOCALE=en_US&VOICE=cmu-bdl-hsmm&AUDIO=WAVE_FILE&effect_F0Scale_selected=on&effect_F0Scale_parameters=f0Scale%3A1.5%3B&effect_TractScaler_selected=on&effect_TractScaler_parameters=amount%3A0.9%3B&effect_F0Add_selected=on&effect_F0Add_parameters=f0Add%3A20.0%3B&effect_Rate_selected=on&effect_Rate_parameters=durScale%3A0.769230769231%3B
http://127.0.0.1:59125/process?INPUT_TYPE=TEXT&OUTPUT_TYPE=AUDIO&INPUT_TEXT=Last%20one&VOICE_SELECTIONS=cmu-bdl-hsmm%20en_US%20male%20hmm&AUDIO_OUT=WAVE_FILE&LOCALE=en_US&VOICE=cmu-bdl-hsmm&AUDIO=WAVE_FILE&effect_F0Scale_selected=on&effect_F0Scale_parameters=f0Scale%3A1.5%3B&effect_TractScaler_selected=on&effect_TractScaler_parameters=amount%3A0.9%3B&effect_F0Add_selected=on&effect_F0Add_parameters=f0Add%3A20.0%3B&effect_Rate_selected=on&effect_Rate_parameters=durScale%3A0.769230769231%3B
http://127.0.0.1:59125/process?INPUT_TYPE=TEXT&OUTPUT_TYPE=AUDIO&INPUT_TEXT=Alright&VOICE_SELECTIONS=cmu-bdl-hsmm%20en_US%20male%20hmm&AUDIO_OUT=WAVE_FILE&LOCALE=en_US&VOICE=cmu-bdl-hsmm&AUDIO=WAVE_FILE&effect_F0Scale_selected=on&effect_F0Scale_parameters=f0Scale%3A1.5%3B&effect_TractScaler_selected=on&effect_TractScaler_parameters=amount%3A0.9%3B&effect_F0Add_selected=on&effect_F0Add_parameters=f0Add%3A20.0%3B&effect_Rate_selected=on&effect_Rate_parameters=durScale%3A0.769230769231%3B
http://127.0.0.1:59125/process?INPUT_TYPE=TEXT&OUTPUT_TYPE=AUDIO&INPUT_TEXT=That%20was%20awesome&VOICE_SELECTIONS=cmu-bdl-hsmm%20en_US%20male%20hmm&AUDIO_OUT=WAVE_FILE&LOCALE=en_US&VOICE=cmu-bdl-hsmm&AUDIO=WAVE_FILE&effect_F0Scale_selected=on&effect_F0Scale_parameters=f0Scale%3A1.5%3B&effect_TractScaler_selected=on&effect_TractScaler_parameters=amount%3A0.9%3B&effect_F0Add_selected=on&effect_F0Add_parameters=f0Add%3A20.0%3B&effect_Rate_selected=on&effect_Rate_parameters=durScale%3A0.769230769231%3B
ERROR    2017-02-13 23:49:31,600 webapp2.py:1552] HTTP Error 400: Bad Request
Traceback (most recent call last):
  File "/Users/brianfeister/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/Users/brianfeister/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/Users/brianfeister/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/Users/brianfeister/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/Users/brianfeister/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/Users/brianfeister/Downloads/google-cloud-sdk/platform/google_appengine/lib/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/Users/brianfeister/dev/aiexperiments-giorgio-cam/server/mary.py", line 51, in get
    audio = urllib2.urlopen(url).read()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
`

**Comment by tambien** [comment]
maybe you don't have the right voice installed? I used the [marytts installer](https://github.com/marytts/marytts-installer) to add the cmu-bdl-hsmm male english voice.

**Comment by tambien** [comment]
Actually before you do that, check that you are running maryTTS on http://127.0.0.1:59125/. You'll need to run it in a different terminal window/tab than the python server. Both the file server and the marytts server run at the same time.

**Comment by brianfeister** [comment]
Yeah the server was running, it was the particular voice that was missing. 

Fixed via `./marytts install:cmu-bdl-hsmm`

Thanks!
